# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/david/githubCode/cProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/david/githubCode/cProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/githubCode/cProject/CMakeFiles /Users/david/githubCode/cProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/githubCode/cProject/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/githubCode/cProject/CMakeFiles /Users/david/githubCode/cProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/githubCode/cProject/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named list0410

# Build rule for target.
list0410: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 list0410
.PHONY : list0410

# fast build rule for target.
list0410/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0410.dir/build.make CMakeFiles/list0410.dir/build
.PHONY : list0410/fast

#=============================================================================
# Target rules for targets named list0418

# Build rule for target.
list0418: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 list0418
.PHONY : list0418

# fast build rule for target.
list0418/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0418.dir/build.make CMakeFiles/list0418.dir/build
.PHONY : list0418/fast

#=============================================================================
# Target rules for targets named list0419

# Build rule for target.
list0419: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 list0419
.PHONY : list0419

# fast build rule for target.
list0419/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0419.dir/build.make CMakeFiles/list0419.dir/build
.PHONY : list0419/fast

#=============================================================================
# Target rules for targets named list0420

# Build rule for target.
list0420: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 list0420
.PHONY : list0420

# fast build rule for target.
list0420/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0420.dir/build.make CMakeFiles/list0420.dir/build
.PHONY : list0420/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named running

# Build rule for target.
running: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 running
.PHONY : running

# fast build rule for target.
running/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/running.dir/build.make CMakeFiles/running.dir/build
.PHONY : running/fast

list0410.o: list0410.c.o
.PHONY : list0410.o

# target to build an object file
list0410.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0410.dir/build.make CMakeFiles/list0410.dir/list0410.c.o
.PHONY : list0410.c.o

list0410.i: list0410.c.i
.PHONY : list0410.i

# target to preprocess a source file
list0410.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0410.dir/build.make CMakeFiles/list0410.dir/list0410.c.i
.PHONY : list0410.c.i

list0410.s: list0410.c.s
.PHONY : list0410.s

# target to generate assembly for a file
list0410.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0410.dir/build.make CMakeFiles/list0410.dir/list0410.c.s
.PHONY : list0410.c.s

list0418.o: list0418.c.o
.PHONY : list0418.o

# target to build an object file
list0418.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0418.dir/build.make CMakeFiles/list0418.dir/list0418.c.o
.PHONY : list0418.c.o

list0418.i: list0418.c.i
.PHONY : list0418.i

# target to preprocess a source file
list0418.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0418.dir/build.make CMakeFiles/list0418.dir/list0418.c.i
.PHONY : list0418.c.i

list0418.s: list0418.c.s
.PHONY : list0418.s

# target to generate assembly for a file
list0418.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0418.dir/build.make CMakeFiles/list0418.dir/list0418.c.s
.PHONY : list0418.c.s

list0419.o: list0419.c.o
.PHONY : list0419.o

# target to build an object file
list0419.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0419.dir/build.make CMakeFiles/list0419.dir/list0419.c.o
.PHONY : list0419.c.o

list0419.i: list0419.c.i
.PHONY : list0419.i

# target to preprocess a source file
list0419.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0419.dir/build.make CMakeFiles/list0419.dir/list0419.c.i
.PHONY : list0419.c.i

list0419.s: list0419.c.s
.PHONY : list0419.s

# target to generate assembly for a file
list0419.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0419.dir/build.make CMakeFiles/list0419.dir/list0419.c.s
.PHONY : list0419.c.s

list0420.o: list0420.c.o
.PHONY : list0420.o

# target to build an object file
list0420.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0420.dir/build.make CMakeFiles/list0420.dir/list0420.c.o
.PHONY : list0420.c.o

list0420.i: list0420.c.i
.PHONY : list0420.i

# target to preprocess a source file
list0420.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0420.dir/build.make CMakeFiles/list0420.dir/list0420.c.i
.PHONY : list0420.c.i

list0420.s: list0420.c.s
.PHONY : list0420.s

# target to generate assembly for a file
list0420.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/list0420.dir/build.make CMakeFiles/list0420.dir/list0420.c.s
.PHONY : list0420.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

running.o: running.c.o
.PHONY : running.o

# target to build an object file
running.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/running.dir/build.make CMakeFiles/running.dir/running.c.o
.PHONY : running.c.o

running.i: running.c.i
.PHONY : running.i

# target to preprocess a source file
running.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/running.dir/build.make CMakeFiles/running.dir/running.c.i
.PHONY : running.c.i

running.s: running.c.s
.PHONY : running.s

# target to generate assembly for a file
running.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/running.dir/build.make CMakeFiles/running.dir/running.c.s
.PHONY : running.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list0410"
	@echo "... list0418"
	@echo "... list0419"
	@echo "... list0420"
	@echo "... main"
	@echo "... running"
	@echo "... list0410.o"
	@echo "... list0410.i"
	@echo "... list0410.s"
	@echo "... list0418.o"
	@echo "... list0418.i"
	@echo "... list0418.s"
	@echo "... list0419.o"
	@echo "... list0419.i"
	@echo "... list0419.s"
	@echo "... list0420.o"
	@echo "... list0420.i"
	@echo "... list0420.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... running.o"
	@echo "... running.i"
	@echo "... running.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

